user_input = int(input("Please enter a number: "))


print(user_input, 'x', 1, '=', user_input*1)
print(user_input, 'x', 2, '=', user_input*2)
print(user_input, 'x', 3, '=', user_input*3)
print(user_input, 'x', 4, '=', user_input*4)
print(user_input, 'x', 5, '=', user_input*5)
print(user_input, 'x', 6, '=', user_input*6)
print(user_input, 'x', 7, '=', user_input*7)
print(user_input, 'x', 8, '=', user_input*8)
print(user_input, 'x', 9, '=', user_input*9)
print(user_input, 'x', 10, '=', user_input*10)
print(user_input, 'x', 11, '=', user_input*11)
print(user_input, 'x', 12, '=', user_input*12)
